# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voting_status',
            new_name='bsen_status',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='category',
        ),
        migrations.AddField(
            model_name='contestant',
            name='random_suppling',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='cult_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='gsen_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='hostel_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='sports_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='tech_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='vp_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='welf_status',
            field=models.BooleanField(default=False),
        ),
    ]
