# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20170211_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='post',
            field=models.CharField(choices=[('VP', 'Vice President'), ('HAB', 'Hostel Affairs Board Seceratary'), ('UGS', 'Under Graduate Senate'), ('PGS', 'Post Graduate Senate '), ('GS', 'Girl Senate'), ('Tech', 'Technical Seceratary'), ('Cult', 'Cultural Seceratary'), ('Welfare', 'Welfare Seceratary'), ('Sports', 'Sports Seceratary')], default='vp', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='category',
            field=models.CharField(choices=[('0', 'UG-Boy'), ('1', 'UG-Girl'), ('2', 'PG-Boy'), ('3', 'PG-Girl')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='random_suppling',
            field=models.IntegerField(default=0),
        ),
    ]
