# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20170211_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 11, 37, 14, 896750)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 11, 37, 27, 866701)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='pic',
            field=models.ImageField(upload_to='images/contestants/'),
        ),
    ]
