# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20170212_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='pic',
            field=models.ImageField(upload_to='contestants/'),
        ),
    ]
