# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20170212_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
