# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20170218_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='dept',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='voter',
            name='hostel',
            field=models.CharField(default='MANAS', max_length=50),
        ),
    ]
