# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_auto_20170219_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='post',
            field=models.CharField(choices=[('VP', 'Vice President'), ('HAB', 'General Secretary of Hostel Affairs Board'), ('UGS', 'Under Graduate Senator'), ('PGS', 'Post Graduate Senator '), ('GS', 'Girl Senator'), ('Tech', 'General Secretary of Technical Board'), ('Cult', 'General Secretary of Cultural Board'), ('Welfare', "General Secretary of Students' Welfare Board"), ('Sports', 'General Secretary of Sports Board'), ('SAIL', 'General Seceratry of SAIL'), ('CBS', 'General Seceratry of CBS')], max_length=7),
        ),
    ]
